# Collections
# Use: ansible-galaxy collection install -r requirements.yml

collections:
  - name: community.mysql
    version: ">=2.0.0"
  - name: grafana.grafana
    version: ">5.5.0"
  #- name: Oefenweb.dnsmasq
  #  version: ">2.2.31"
  - name: community.zabbix
