---
#*************************************************************************
# Group_Vars used mainly by various roles
#*************************************************************************

#**************************************
# Groups
#**************************************
strict_gid: true   # Enforce group definitions in the role
my_groups:
  - users
  - db
  - backup
  - analytics

#**************************************
# Accounts
#**************************************
my_accounts:
  - name: marrh
  - name: bakerj
    primary_group: awx
  - name: petersoni
    primary_group: awx
  - name: mysql
    primary_group: db
    secondary_groups:
      - backup
      - analytics

#**************************************
# Public SSH Keys
#**************************************
my_keys_to_deploy:
  marrh:
    keys:
      - marrh
  bakerj:
    keys:
      - bakerj
      - access001

#**************************************
# Manage Packages
#**************************************
my_packages_install:
  - nfs-utils
  - binutils
  - nfs-utils
  - traceroute

my_packages_uninstall:

my_packages_enable_repo:

#**************************************
# motd
#**************************************
motd_template: motd01.j2

#**************************************
# resolver
#**************************************
my_resolver: mainchain

#**************************************
# Services
#**************************************
my_services_enable:
my_services_disable:
my_services_start:
my_services_stop:

#**************************************
# sysctl.conf
#**************************************
legacy_sysctl: true
sysctl_settings:
  99-ansible-local: 
    - name: net.ipv4.ip_forward
      value: 1
    - name: vm.swappiness
      value: 10
  99-database: 
    - name: net.ipv4.ip_forward
      value: 1

#**************************************
# SCAP Reporting
#**************************************
scap_report: true
scap_report_dir: "scap_reports"

# Get profiles using cmd: oscap info /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
# CIS Red Hat Enterprise Linux 9 Benchmark for Level 1 - Server
scap_profile: "xccdf_org.ssgproject.content_profile_cis_server_l1"

# CIS Red Hat Enterprise Linux 9 Benchmark for Level 2 - Server
#scap_profile: "xccdf_org.ssgproject.content_profile_cis"



